<a href="https://colab.research.google.com/github/Kaifjamadar/Internship/blob/main/Task_1/Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
k = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print (k)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
sum = np.array([[24+45]])
print (sum)


[[69]]


In [ ]:
import numpy as np
a = np . arange (4)
print (a)


[0 1 2 3]


In [ ]:
import numpy as np
value = np . arange(3,9)
print (value)


[3 4 5 6 7 8]
